<?php /* @var $this Solvingmagento_OneStepCheckout_Block_Onestep_Shipping */ ?>
<?php
/**
 * Solvingmagento_OneStepCheckout shipping step template
 *
 * PHP version 5.3
 *
 * @category  Solvingmagento
 * @package   Solvingmagento_OneStepCheckout
 * @author    Magento Core Team <core@magentocommerce.com>
 * @author    Oleg Ishenko <oleg.ishenko@solvingmagento.com>
 * @copyright Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com), 2014 Oleg Ishenko
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @version   GIT: <0.1.0>
 * @link      http://www.solvingmagento.com/
 *
 */
?>
<div class="cart-right-title">
    Shipping address
</div>
<div class="checkout-clear-both"></div>

<form action="" id="co-shipping-form">
    <input type="hidden" name="shipping[new_address]" value="<?php echo $this->customerHasAddresses()?'0':'1' ?>" class="targetShippingIf">
    <ul class="form-list">
        <?php if ($this->customerHasAddresses()): ?>
            <li class="fields" id="shipping-address-select">
                <div class="input-box">
                    <select name="shipping_address_id" class="validate-select required-entry shipping-address-select">
                        <?php foreach ($this->getCustomer()->getAddressesCollection() as $_addr): ?>
                            <option <?php echo ($this->getDefaultAddress() == $_addr->getId()) ? 'selected' : '' ?>
                                value="<?php echo $_addr->getId() ?>"><?php echo $this->escapeHtml($_addr->format('oneline')) ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </li>
        <?php endif ?>
        <?php if($this->customerHasAddresses()): ?>
        <li><a href="#" class="add-shipping-address"><?php echo $this->__('New Address') ?></a></li>
        <?php endif; ?>
        <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
            <?php if ($this->customerHasAddresses()): ?>
                <a href="#" class="cancel-add-address">Cancel New Address</a>
            <?php endif ?>
            <div>
                <input
                    type="hidden"
                    name="shipping[address_id]"
                    value="<?php echo $this->getAddress()->getId() ?>"
                    id="shipping:address_id" />
                <ul>
                    <li class="fields"><?php
                        echo $this->getLayout()
                            ->createBlock('customer/widget_name')
                            ->setObject($this->getAddress())
                            ->setFieldIdFormat('shipping:%s')
                            ->setFieldNameFormat('shipping[%s]')
                            ->setFieldParams('onchange="shipping.setSameAsBilling(false)"')
                            ->toHtml()
                        ?></li>
                    <li class="fields">
                        <div class="field">
                            <label for="shipping:company"><?php echo $this->__('Company') ?></label>
                            <div class="input-box">
                                <input
                                    type="text"
                                    id="shipping:company"
                                    name="shipping[company]"
                                    value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>"
                                    title="<?php echo $this->__('Company') ?>"
                                    class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>"
                                    onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </div>
                    </li>
                    <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                    <li class="field">
                        <label for="shipping:street1" class="required"><em>*</em> <?php echo $this->__('Address') ?></label>
                        <div class="input-box">
                            <input
                                type="text"
                                title="<?php echo $this->__('Street Address') ?>"
                                name="shipping[street][]"
                                id="shipping:street1"
                                value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>"
                                class="input-text <?php echo $_streetValidationClass ?>"
                                onchange="shipping.setSameAsBilling(false);" />
                        </div>
                    </li>
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                        <li class="fields">
                            <label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>
                            <div class="input-box">
                                <input
                                    type="text"
                                    id="shipping:vat_id"
                                    name="shipping[vat_id]"
                                    value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>"
                                    title="<?php echo $this->__('VAT Number'); ?>"
                                    class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                            </div>
                        </li>
                    <?php endif; ?>
                    <li class="fields">
                        <div class="two-fields">
                            <div class="field">
                                <label for="shipping:city" class="required"><em>*</em> <?php echo $this->__('City') ?></label>
                                <div class="input-box">
                                    <input
                                        type="text"
                                        title="<?php echo $this->__('City') ?>"
                                        name="shipping[city]"
                                        value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"
                                        class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>"
                                        id="shipping:city" onchange="shipping.setSameAsBilling(false);" />
                                </div>
                            </div>
                            <div class="field">
                                <label for="shipping:postcode" class="required"><em>*</em> <?php echo $this->__('Zip/Postal Code') ?></label>
                                <div class="input-box">
                                    <input
                                        type="text"
                                        title="<?php echo $this->__('Zip/Postal Code') ?>"
                                        name="shipping[postcode]"
                                        id="shipping:postcode"
                                        value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
                                        class="input-text validate-zip-international <?php
                                        echo $this->helper('customer/address')->getAttributeValidationClass('postcode')
                                        ?>"
                                        onchange="shipping.setSameAsBilling(false);" />
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="field">
                            <label for="shipping:country_id" class="required"><em>*</em> <?php echo $this->__('Country') ?></label>
                            <div class="input-box country-select-container-alt">
                                <?php echo $this->getCountryHtmlSelect('shipping') ?>
                            </div>
                        </div>
                        <div class="field">
                            <label for="shipping:region" class="required"><em>*</em> <?php echo $this->__('State/Province') ?></label>
                            <div class="input-box">
                                <select
                                    id="shipping:region_id"
                                    name="shipping[region_id]"
                                    title="<?php echo $this->__('State/Province') ?>"
                                    class="validate-select cart-province-select-alt"
                                    style="display:none;">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                    //<![CDATA[
                                    $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                    //]]>
                                </script>
                                <input
                                    type="text"
                                    id="shipping:region"
                                    name="shipping[region]"
                                    value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"
                                    title="<?php echo $this->__('State/Province') ?>"
                                    class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?> cart-province-text-alt"
                                    style="display:none;" />
                            </div>
                        </div>
                    </li>
                    <li class="fields">
                        <div class="two-fields">
                            <div class="field">
                                <label for="shipping:telephone" class="required"><em>*</em> <?php echo $this->__('Telephone') ?></label>
                                <div class="input-box">
                                    <input
                                        type="text"
                                        name="shipping[telephone]"
                                        value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>"
                                        title="<?php echo $this->__('Telephone') ?>"
                                        class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>"
                                        id="shipping:telephone"
                                        onchange="shipping.setSameAsBilling(false);" />
                                </div>
                            </div>
                            <div class="field">
                                <label for="shipping:fax"><?php echo $this->__('Fax') ?></label>
                                <div class="input-box">
                                    <input
                                        type="text"
                                        name="shipping[fax]"
                                        value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>"
                                        title="<?php echo $this->__('Fax') ?>"
                                        class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>"
                                        id="shipping:fax"
                                        onchange="shipping.setSameAsBilling(false);" />
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1"/></li>
                </ul>
            </div>
        </li>
        <li class="control shipp-as-billing" style="display:none!important;">
            <input
                type="checkbox"
                name="shipping[same_as_billing]"
                id="shipping:same_as_billing"
                value="0"
                title="<?php echo $this->__('Use Billing Address') ?>"
                onclick="shipping.setSameAsBilling(this.checked)"
                class="checkbox" />
            <label for="shipping:same_as_billing"><?php echo $this->__('Use Billing Address') ?></label>
        </li>
    </ul>
    <span id="shipping-please-wait" class="please-wait" style="display:none;">
        <img
            src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"
            alt="<?php echo $this->__('Loading next step...') ?>"
            title="<?php echo $this->__('Loading next step...') ?>"
            class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
    </span>
</form>
<script type="text/javascript">
    //<![CDATA[
    var shippingForm = new VarienForm('co-shipping-form');
    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    //$('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJsonByStore() ?>, undefined, 'shipping:postcode');
    //]]>
</script>
