<?php
/**
 * Solvingmagento_OneStepCheckout review step info template
 *
 * PHP version 5.3
 *
 * @category  Solvingmagento
 * @package   Solvingmagento_OneStepCheckout
 * @author    Magento Core Team <core@magentocommerce.com>
 * @author    Oleg Ishenko <oleg.ishenko@solvingmagento.com>
 * @copyright Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com), 2014 Oleg Ishenko
 * @license   http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @version   GIT: <0.1.0>
 * @link      http://www.solvingmagento.com/
 *
 */
?>
<?php echo $this->getChildHtml('items_before'); ?>
<style>
    .gift-message-container,#osc-column-bottom .cart-btns{
        display:block;
    }
</style>
<div id="checkout-review-table-wrapper">
    <table id="shopping-cart-table" class="data-table cart-table cart-checkout-table">
        <thead>
        <tr>
            <th class="t-remove"><?php echo $this->__('Remove') ?></th>
            <th class="t-image"></th>
            <th class="t-name"><?php echo $this->__('Item') ?></th>
            <th class="t-price"><?php echo $this->__('Price') ?></th>
            <th class="t-quantity"><?php echo $this->__('Quantity') ?></th>
            <th class="t-total"><?php echo $this->__('Total') ?></th>
        </tr>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <tr>
                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
            </tr>
        <?php endif; ?>
        </thead>
        <?php echo $this->getChildHtml('totals'); ?>
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
<?php echo $this->getChildHtml('items_after'); ?>
<script type="text/javascript">
    //<![CDATA[
    decorateTable('checkout-review-table');
    truncateOptions();
    //]]>
</script>


<script>
    jQuery(function(){

        jQuery('.quantity_box_button_up').click(function(e) {
            e.preventDefault();
            var oldVal = jQuery(this).parent().find(".input-text-qty").val();
            if ( parseFloat(oldVal) >= 1 ) {
                var newVal = parseFloat(oldVal) + 1;
                jQuery(this).parent().find(".input-text-qty").val(newVal);
            }
        });

        jQuery('.quantity_box_button_down').click(function(e) {
            e.preventDefault();
            var oldVal = jQuery(this).parent().find(".input-text-qty").val();
            if ( parseFloat(oldVal) > 1 ) {
                var newVal = parseFloat(oldVal) - 1;
                jQuery(this).parent().find(".input-text-qty").val(newVal);

            }
        });

    });
</script>