<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/theme.css') ?>" type="text/css" media="all" />
<link rel="stylesheet" href="<?php echo $this->getSkinUrl('css/fonts/SanFrancisco/lightondark.css') ?>" type="text/css" media="all" />
<style>
    body {
        color: #ffffff !important;
        background-color: transparent !important;
        font-family: 'San Francisco Text', sans-serif;
        padding: 15pt !important;
    }
    .container-tos .tos-page-title {
        color: #ffffff !important;
    }
    h1, h2, h3, h4, h5, h6 {
        color: #ffffff !important;
    }
</style>
<div class="container-tos clearfix">
    <div class="clearfix">
        <div class="col-main-tos-inner">
            <div class="tos-page-title">
                About Under 100
            </div>
            <div class="std">
                <p>Under 100 is a social marketplace where users can Discover, Buy, and Share Amazing things that are all Under $100 in price.</p>
                <p>We enable users to discover products on a whole new level by using our community's interactions to determine product popularity and curate content.</p>
                <p>Users can buy any item they see as they filter, sort, and tailor our feed, as well as browse our unique sales, deals, and product categories.</p>
                <p>Brands and users can easily share products on our platform by entering a product's original URL (our software pulls all product information), and receive a commission on sales of any products they post.</p>
                <p>We provide a comfortable, relaxing, and safe experience by aggregating all of the products you want to shop for in one centralized place where you can browse knowing that you will never break your bank, as every product is Under $100 in price.</p>
                <p>&nbsp;</p>
                <div>
                    <h1>Our Story</h1>
                </div>
                <p>Under 100 was founded by Cole Glass, who came up with the idea during a road trip to Los Angeles while discussing his frustrations with current online shopping offerings with his girlfriend. They lamented the fact that there was no centralized online marketplace where they could discover cool, new products that were most popular with today's enormous online shopping population and fit within their (and most people's) budgets. Then, Cole decided to create such a place by leveraging social curation of content, aggregation of products across all shopping categories, and an incredibly attractive $100 price ceiling.</p>
                <p>Since that road trip, Cole has worked tirelessly for almost a year using his own salary and some help from friends and family to turn the idea for Under 100 into a real business and platform.</p>
            </div>
        </div>
    </div>
</div>